### ISSUE TITLE
Fix for CSRF

### ISSUE THREAD

**Issue by newerton** [2amigos/yii2-grid-view-library#1]
Was having problems updating some items in the GridView.

EditableColumn.php - line 143

``` php
$js[] = ";jQuery('$selector').editable({params: function(params) { params._csrf = '".\Yii::$app->getRequest()->csrfToken."'; return params; }});";
```

**Comment by gb5256** [comment]
I would like to re-open this issue.
I am using latest yii2-advanced template with the <?= Html::csrfMetaTags(); ?> in the main layout.
But I do not see the _crsf submitted on the editableColumn.
Any Idea?
