### ISSUE TITLE
editable column - select

### ISSUE THREAD

**Issue by BARTlab** [2amigos/yii2-grid-view-library#16]
This code show emty value

```
[
    'class' => \dosamigos\grid\EditableColumn::className(),
    'type' => 'select',
    'url' => ['update'],
    'attribute' => 'category_id',
    'editableOptions'=>[
        'autotext'=>'always',
        'source' => json_encode($section)
    ]
],
```

This occurs because js plug-in for some reason does not get the right value.

Quick fix:

```
'editableOptions'=>function($model, $key, $index) use ($section){
    return [
        'value'=>$model->category_id,
        'autotext'=>'always',
        'source' => json_encode($section)
    ];
}
```

But, may want add to the EditableColumn widget code?

```
    protected function renderDataCellContent($model, $key, $index)
    {

        ...
        $this->options['data-value'] = $value;

      ...
    }
```

**Comment by BARTlab** [comment]
You have written a very bad example. In the first case - we do not know the variable $model, in the second - when you open the editing popup window - do not select the correct option

**Comment by BARTlab** [comment]
And, format = 'raw' autoset:
https://github.com/2amigos/yii2-grid-view-library/blob/master/EditableColumn.php#L70

**Comment by BARTlab** [comment]
and how about this?
https://github.com/2amigos/yii2-editable-widget/blob/master/assets/editable/js/bootstrap-editable.js#L490

**Comment by ybreeze** [comment]
You are right about 'format', it's 'raw' by default and can be skipped.

You are not right about $model. Please read official guide for GridView - http://www.yiiframework.com/doc-2.0/guide-output-data-widgets.html - "Grid columns" section.
$model (or $data in guide) is know and will be passed by GridView  to 'value' function for each grid row from $dataProvider.

you can specify type of $model like -
``` php
    'value' => function(Company $model) {
        return $model->getCategoryName();
    },
```
for IDE autocomplete etc.

**Comment by BARTlab** [comment]
I have looked to the source code, and once again I can tell you - your way is not correct, read the bootstrap-editable.js code

**Comment by ybreeze** [comment]
"your way is not correct" - It is works perfect in my project.

"For __select__ type should be defined (as it is ID of shown text)." - 
``` php
    'editableOptions' => [
        ...
        'source' => [
            [
                'value' => 1,
                'text' => 'Active',
            ],
            [
                'value' => 0,
                'text' => 'Inactive',
            ]
        ],
        'placement' => 'bottom',
        ...
    ]
```

**Comment by BARTlab** [comment]
```
 'editableOptions' => [
        ...
        'source' => [
            [
                'value' => 1,
                'text' => 'Active',
            ],
            [
                'value' => 0,
                'text' => 'Inactive',
            ]
        ],
        ...
    ]
```

htmlspecialchars() expects parameter 1 to be string, array given
in /var/www/imperia/common/lib/vendor/yiisoft/yii2/helpers/BaseHtml.php  at line 96

**Comment by BARTlab** [comment]
```
[
                'class' => \dosamigos\grid\EditableColumn::className(),
                'type' => 'select',
                'url' => ['update'],
                'attribute' => 'group_id',
                'value' => function ($model) {
                    return 'Active';
                },
                'editableOptions' => [
                    'source' => json_encode(
                        [
                            [
                                'value' => 1,
                                'text' => 'Active',
                            ],
                            [
                                'value' => 2,
                                'text' => 'Inactive',
                            ]
                        ]
                    ),
                ]
            ],
```
when you open the editing popup window - do not select the correct option
![s_42](https://cloud.githubusercontent.com/assets/889330/5602501/3812aa5a-935a-11e4-87b5-f89f15079f3f.png)

**Comment by tonydspaniard** [comment]
@BARTlab Will review it personally whenever I have time

**Comment by gb5256** [comment]
I have the same issue. The field does not show the current value as default. If somebody has a solution for this it would be highly appreciated to post an example.

**Comment by re1naldo** [comment]
@tonydspaniard Any updates regarding this issue? Does select2 not show the correct option because it uses displayed column value (instead of column ID)?

**Comment by tonydspaniard** [comment]
new updates: http://yii2-grid-view-library.readthedocs.io/en/latest/
