### ISSUE TITLE
Is it possible to set the type of the column dynamically?

### ISSUE THREAD

**Issue by gb5256** [2amigos/yii2-grid-view-library#18]
Hi,
I have something like this:

```
  'class' => \dosamigos\grid\EditableColumn::className(),
                    'attribute' => 'value',
                    'url' => ['editable'],
                    'type' => function($model) { return $model->type; },
```

I do store in my model also a 'Type' attribute, as some users should see a drop down, other not.
But the above does throw an error:
htmlspecialchars() expects parameter 1 to be string, object given.
I tried already (just to see if it is working) to set the type without the model, like this:

```
     'type' => function($model) { return 'text'; },
```

Gives me the same error. I can do that on values, etc but not on the type. 
hmmm. 
is there a workaroud?

**Comment by tonydspaniard** [comment]
Unfortunately not at this time. That is an issue with the render attributes of Yii itself.
