### ISSUE TITLE
Docs for GroupGridView

### ISSUE THREAD

**Issue by Maximilan4** [2amigos/yii2-grid-view-library#21]
Can you add any docs for using GroupGridView ?

**Comment by tonydspaniard** [comment]
Works like http://yiiwheels.2amigos.us/site/grid#groupgridview 

I'll add more docs. Sorry for the inconvenience and the late reply.

**Comment by tonydspaniard** [comment]
@Maximilan4 the grid library has changed completely, is very powerful now. GroupGridView has been transformed into a behavior: http://yii2-grid-view-library.readthedocs.io/en/latest/
