### ISSUE TITLE
Demo link?

### ISSUE THREAD

**Issue by blacksmoke26** [2amigos/yii2-grid-view-library#22]
Please can you provide the demo link before downloading that whole thing?

**Comment by tonydspaniard** [comment]
@blacksmoke26 very sorry for late response. I really need to add that. Didn't have much time lately. We will update our site for demoing all our components in near future.

**Comment by blacksmoke26** [comment]
Ah no problem! I got that!

**Comment by tonydspaniard** [comment]
@blacksmoke26 check the new docs!
