### ISSUE TITLE
Columns loose editable after sorting of grid?

### ISSUE THREAD

**Issue by gb5256** [2amigos/yii2-grid-view-library#25]
Hello,
After I am sorting a grid by clicking on a header, the editability of the cells vanishes.

Is this a bug?
Any ideas?

gb5256

**Comment by tonydspaniard** [comment]
@gb5256 that is due to the use of pjax. After ajax, edition capabilities are lost. We need to add a function to re-initialize the editable objects.

**Comment by tonydspaniard** [comment]
@gb5256 updated
