### ISSUE TITLE
Class namespace incorrect in latest version?

### ISSUE THREAD

**Issue by canreo** [2amigos/yii2-grid-view-library#27]
### What steps will reproduce the problem?
use dosamigos\grid\ToggleAction;

### What do you get instead?
"Class 'dosamigos\grid\ToggleAction' not found"

Had to change to:
use dosamigos\grid\actions\ToggleAction;
and
use dosamigos\grid\column\ToggleColumn;

**Comment by tonydspaniard** [comment]
@canreo the new version has been totally updated and breaks BC. The new classes are: 

- https://github.com/2amigos/yii2-grid-view-library/blob/master/src/actions/ToggleAction.php#L10 
- https://github.com/2amigos/yii2-grid-view-library/blob/master/src/columns/ToggleColumn.php#L10
