### ISSUE TITLE
Class 'dosamigos\editable\EditableBootstrapAsset' not found

### ISSUE THREAD

**Issue by halumein** [2amigos/yii2-grid-view-library#30]
Class 'dosamigos\editable\EditableBootstrapAsset' not found

vendor\2amigos\yii2-grid-view-library\src\columns\EditableColumn.php : 13
use dosamigos\editable\EditableBootstrapAsset; // <- not exist

vendor\2amigos\yii2-grid-view-library\src\columns\EditableColumn.php : 145 
EditableBootstrapAsset::register($view); // <- called here

**Comment by tonydspaniard** [comment]
Have you installed: https://github.com/2amigos/yii2-grid-view-library/blob/master/composer.json#L30 ?

**Comment by halumein** [comment]
After reinstall (delete "yii2-editable-widget" from vendor folder and "composer update" ) looks like trouble gone away. Thanks a lot anyway!
