### ISSUE TITLE
Class GroupColumnsBehavior does not exist

### ISSUE THREAD

**Issue by miladhashemi** [2amigos/yii2-grid-view-library#31]
Hi 2amigos
when in behaviors i use GroupColumnsBehavior as class it shows me:
ReflectionException

Class GroupColumnsBehavior does not exist

**Comment by tonydspaniard** [comment]
Can you show your code? Thanks

**Comment by miladhashemi** [comment]
use dosamigos\grid\GridView;
use dosamigos\grid\behaviors\GroupColumnsBehavior;


<?= GridView::widget([
    'behaviors' => [
        [
            'class' => 'GroupColumnsBehavior',
            // You an use multiple columns for extra row but remember that will affect the merging
            // as both columns must be having same values for the extra row to title the records
            'extraRowColumns' => ['category'],
            // you can use multiple columns here
            'mergeColumns' => ['category']
        ]
    ],
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'group_name',
            'description',
            'category',
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

**Comment by tonydspaniard** [comment]
You forgot to add the namespace to the class

**Comment by miladhashemi** [comment]
i'm new to Yii.
the grid view is in view. is it necessary to use namespace?
I add namespace but the result is same.

**Comment by miladhashemi** [comment]
![viewfile](https://user-images.githubusercontent.com/5060331/31128988-346de0cc-a860-11e7-89c0-893593bf615f.jpg)

![error](https://user-images.githubusercontent.com/5060331/31129068-65d9084e-a860-11e7-9976-79c3f767e321.jpg)

**Comment by tonydspaniard** [comment]
@miladhashemi you forgot to add the namespace of the class: 

```php 
<?= GridView::widget([ 'behaviors' => [ [ 'class' => 'dosamigos\grid\behaviors\GroupColumnsBehavior' // <-------- here

**Comment by harrisonalwanga** [comment]
I found the same error the above did not solve my problem any other solution?
