### ISSUE TITLE
Make GroupColumnsBehavior work with ActionColumn

### ISSUE THREAD

**Issue by tonydspaniard** [2amigos/yii2-grid-view-library#33]
### What steps will reproduce the problem?
Using GroupColumnsBehavior fails to display ActionColumns

### What is the expected result?
ActionColumn buttons to be displayed

### What do you get instead?
Error

**Comment by tonydspaniard** [comment]
re #32

**Comment by tonydspaniard** [comment]
Same issue with SerialColumn

**Comment by adiramardiani** [comment]
Any progress with this issues ?

**Comment by Krakozaber** [comment]
It fix by https://github.com/2amigos/yii2-grid-view-library/pull/29, but there hasn't been a release yet!

**Comment by tonydspaniard** [comment]
done @Krakozaber
